### ISSUE TITLE
Best ways to leverage Less of Bootstrap with Bootlint?

### ISSUE THREAD

**Issue by fabm22** [twbs/bootlint#291]
If I want to both use Less of Bootstrap and at same time use what Bootlint can give as confidence in results testing, is there some practices I should follow ?

Like, I don't know, should I avoid creating new classes (like new more semantic classes for a project) since I guess those can't be validate by Bootlint, right ?

Thanks for help

**Comment by zacechola** [comment]
Bootlint has some strong expectations about structure of the HTML.

>Bootlint is a tool that checks for several common HTML mistakes in webpages that are using Bootstrap in a fairly "vanilla" way. Vanilla Bootstrap's components/widgets require their parts of the DOM to conform to certain structures.

So if, in Less, you create a new class (such as semantic column names), Bootlint won't help you, since the nature of Bootstrap changes for your situation.

That said, any structures you leave alone, you can certainly continue to test. If Bootlint gives you guff about something you intended to change, you can always disable any problem IDs.
