### ISSUE TITLE
Why exist bower.json?

### ISSUE THREAD

**Issue by evilebottnawi** [twbs/bootlint#330]
I like bower and install from bower this package, but get error now due to this file.

**Comment by zacechola** [comment]
What is the error?

**Comment by cvrebert** [comment]
Because if we didn't have it, we'd get issues or pull requests from folks trying to add Bower support in vain ("Oh, the file isn't there. They just must not have heard of Bower before! I can fix that!").
Bootlint deliberately doesn't support Bower.

**Comment by evilebottnawi** [comment]
@cvrebert Interesting. Why bootlint deliberately doesn't support Bower?

**Comment by cvrebert** [comment]
Because Bower isn't sufficiently actively maintained these days. I don't wish to endorse the usage of (nor have to deal with the shortcomings of) underpowered/mediocre package managers that have little/uncertain prospects of being improved when better alternatives (e.g. npm, jspm) are already available.
See also https://github.com/rackt/redux/issues/944#issuecomment-154858804

**Comment by evilebottnawi** [comment]
@cvrebert thanks for answer
